Use storage.sync
sindresorhus/notifier-for-github pull request #112
Opened 2016-12-24 18:18 UTC by YurySolovyov

Fixes #39 
Also uses async/await and bumps chrome version to 55 to have native async/await support.
Babel is only needed to make it possible for webpack to get build passing because of async/await syntax, no transpilation should occur.
- [ ] Fix tests

Any comments are welcome.

2016-12-27 01:13 UTC, sindresorhus requested changes

2016-12-27 01:13 UTC, sindresorhus commented on extension/manifest.json
> +	"version": "3.0.2",
Don't bump this. Should be done only when actually publishing.

2016-12-27 01:13 UTC, sindresorhus commented on extension/src/persistence-service.js
> +			chrome.storage.sync.set({[name]:value}, () => {
```js
chrome.storage.sync.set({[name]: value}, () => {
```

2016-12-27 01:13 UTC, sindresorhus commented on webpack.config.js
> +					"plugins": ["syntax-async-functions"]
Single-quotes

2016-12-27 01:14 UTC, sindresorhus commented
Nice! Any intention of migrating the old localstorage settings to `chrome.sync`? Would be annoying for users if they had to input their token again.

2016-12-27 08:03 UTC, YurySolovyov commented
I thought about that. For how long are you proposing to keep it?

2017-01-01 11:10 UTC, sindresorhus commented
> For how long are you proposing to keep it?

I assume you mean the migration code. It would be in a separate file, so we could just keep it for a long time. We would migrate the code once on update, so we can just completely switch to `chrome.storage`. Should use the [`onInstalled`](https://developer.chrome.com/extensions/runtime#event-onInstalled) even to detect an update and check if it's an older version that needs the migration and then run the migration script.

2017-07-17 13:54 UTC, sindresorhus commented
@YurySolovyov Is this something you think you'll finish eventually or should I close? I'm trying to clean up stale PRs/issues.

2017-07-17 13:56 UTC, YurySolovyov commented
Close this one, I'll reopen if/when I get back to it.

2017-07-17 14:09 UTC, closed without merging

2018-04-25 16:17 UTC, MasterOfTheTiger commented
How far is thing along?

2018-04-25 16:52 UTC, YurySolovyov commented
I think CI passed a couple of times, but I didn't implement migrator. This can probably be split into 3 parts:
- use async/await
- use storage.sync
- implement migrator from localstorage to storage.sync

I think it was my mistake in trying to do all at once.
If anyone finds anything of this useful, feel free to use it.