Remove hardcoded protocol for notification page URL
sindresorhus/notifier-for-github pull request #210
Opened 2020-04-21 19:56 UTC by Hydrog3n

Fixing issue #198 

I created another function who gets the `rootUrl` and processing like removing the last `/` if exist and if `api.github.com` it's will return github website.

Maybe the better way is to create another option?

2020-04-26 16:53 UTC, notlmn requested changes
I like this change, non-destructive for most and we already ask user to include protocol as well in input.

2020-04-26 16:53 UTC, notlmn commented on source/lib/api.js
> +	if (/(^(https:\/\/)?(api\.)?github\.com)/.test(rootUrl)) {
I think it's a good time for us to move from regex check here to proper URL parsing

Something like this:

```suggestion
	if ((new URL(rootUrl)).origin === 'https://api.github.com) {
```

2020-05-27 08:38 UTC, fregante commented
You should replace `getHostname` instead of adding a new function; it does the same thing and is used everywhere already.

It should probably be renamed for clarity too

```js
export async function getGitHubOrigin() {
	const {rootUrl} = await optionsStorage.getAll();
	const {origin} = new URL(rootUrl);
	return origin === 'https://api.github.com' ? 'https://github.com' : origin;
}
```

2020-07-03 09:54 UTC, Hydrog3n commented
Thank you @notlmn I don't have time to continue my PR sorry.

2020-07-03 09:56 UTC, notlmn commented
No problem @Hydrog3n, I am just cleaning up stuff that have been stale for too long. Thanks for you other contributions.

2020-07-03 10:06 UTC, notlmn commented
We should actually use `https://github.com` in options for `rootUrl` instead of `https://api.github.com`. Ideally should be done through migrations.

Merging this for now.

2020-07-03 10:06 UTC, merged