Allow any query for `/notifications`
sindresorhus/notifier-for-github pull request #299
Opened 2024-09-11 14:10 UTC by scarf005

resolves #296

2024-09-14 13:02 UTC, notlmn requested changes

2024-09-14 13:02 UTC, notlmn commented on source/lib/tabs-service.js
> +			matchingUrls.push(url + '?query=*');
The canonical link to the notifications page is `https://github.com/notifications`, not `https://github.com/notifications?query=` which you could be using here.

The code looks for any tabs that have `/notifications` or `/notifications?query=is%3Aunread`.

The actual fix here should be adding another matching URL to look for.

```suggestion
			matchingUrls.push(url + '?query=');
			matchingUrls.push(url + '?query=is%3Aunread');
```

This also does not require you to use the `new URL(url).pathname`, the param being passed to this function would always be a constant.

2024-09-14 13:46 UTC, scarf005 commented on source/lib/tabs-service.js
> +			matchingUrls.push(url + '?query=*');
applied in [`1e30721` (#299)](https://github.com/sindresorhus/notifier-for-github/pull/299/commits/1e307217a11db749fd8205183005fd001e88b126).

2024-09-15 06:31 UTC, notlmn approved these changes

2024-09-15 06:32 UTC, merged

2024-09-15 06:34 UTC, notlmn commented
Merged this, but beware that publishing to AMO is paused due to lack of full support of MV3. Further context in #298.